* Название:
Erlang на практике

* Описание:
Практические навыки разработки на языке Erlang

* Содержание:
Курс расчитан на программистов, имеющих опыт веб-разработки на любом языке программирования,
но не знакомых или слабо знакомых с Erlang.

Цель курса -- дать практические навыки работы с Erlang/OTP и познакомить
с инфраструктурой вокруг языка: инструментами и библиотеками.

Курс практический, это значит, что в нем много упражнений и небольших проектов, но мало теории.
Некоторые особо важные темы я расскажу. Но подразумевается, что слушатели самостоятельно прочитают
одну из книг по Erlang (до прохождения курса или паралельно с прохождением).

На сегодняшний день есть много хороших книг по Erlang. 2 из них даже переведены на русский язык.

Я рекомендую книгу Фреда Хеберта "Изучай Erlang во имя добра!". Она просто отличная, и мне нет
никакого смысла соревноваться с Фредом в изложении теории :)

Бесплатная версия (html, на английском):
http://learnyousomeerlang.com/content

Электронная и бумажная версия (на английском):
http://www.nostarch.com/erlang

Бумажная версия, русский перевод:
http://www.ozon.ru/context/detail/id/28953563/
