* Designing for <anything> with Erlang
https://medium.com/@dmitriid/designing-for-anything-with-erlang-cfadb6833bc0#.ctwsdsq0g

пост о том, чего не хватает в книгах по эрлангу

it would be really nice to read up on at least some of these things:
    setting up multiple nodes
    testing a distributed app
    deploying a distributed app
    handling failover
    handling load balancing
    handling netsplits (and not only in Mnesia. If we can add a process on node B to a gen_supervisor on node A, how do we handle netsplits, timeouts, restarts etc.?)
    discovery of nodes
    tracing
    profiling
    various VM options and their impact
    securing connection between nodes
    logging
    debugging
    crash dumps
    remote inspection
    mitigating overflowing mailboxes
    SSL
    sockets
    working from behind firewalls
    flood protection
    slow requests
    timeouts
    sessions
    latency
    <add your own>


* Дополнительные темы

+ композиция функций
  сделал в отдельном репозитории
  https://github.com/yzh44yzh/erl_fun_composition

- невозможность циклических структур
  но можно сделать граф, сохраняя инфу о вершинах и ребрах в map или в ets

- инроспекция, трассировка, профилирование
  вот это важная тема, хорошо бы сделать

- bit syntax

- память потока и сборщик мусора

- модель акторов

- raft
Что с этим делать? Включить в этот курс, или в другой?


* Август 2018

Група 8 человек
5 занятий по 4 часа


* Август 2016

Читал 2 раза для групп по 10 человек. 4 занятия по 4 часа -- 16 часов.

1-я группа
1-е занятие: 1-3 темы
2-е занятие: 4-6 темы
3-е занятие: 7-9 темы
4-е занятие: 10-15 темы (только теория)
16-ю тему не успел.

2-я группа
1-е занятие: 0-2 темы
2-е занятие: 3-5 темы
3-е занятие: 6-8 темы
4-е занятие:


16 часов мало, нужно 20.
Оптимально: 5 занятий по 4 часа.
Можно 4 занятия по 5 часов.
Эсктремально: 3 занятия по 6 часов (это если проводить с выездом в другой город).

У 2й группы были трудности с практикой. Функциональная парадигма для многих оказалась неизвестной.
Возможно есть смысл в отдельном курсе "Основы функционального программирования". Можно на базе Elixir :)
