* TODO 2й урок

** TODO теория

https://github.com/yzh44yzh/erlang-school/blob/master/01_t_erlang_base/src/base.erl
посмотреть, что тут есть по теме

прочитать:
OTP in Action
2.2.10 Understanding lists
appendix B Lists and referential transparency


- схема устройтва списка
- схема памяти для cons
- схема устройства двунаправленного списка
- схема памяти для cons двунаправленного
- схема устройства массива, модификация памяти на месте

неизменяемые переменные
как так получается, что список меняется, оставаясь неизменным? )

- операции над списками. Для каждой алгоритмическая стоимость и схема памяти. Сравнение с массивами
  - добавить в начало списка - 1
  - добавить в конец списка - O(n)
  - определить длинну списка - O(n)
  - получить N-й элемент - O(n)
  - конкатернация двух списков - O(n)
  - первый список копируется, второй реюзается. Стоимость -- длинна первого списка

вывод, почему массивы не используются
К слову, массив (array) в эрланге тоже есть.
это не тип данных, это модуль. Упомяну его тут, чтобы потом забыть и больше не вспоминать :)
Это не настоящие массивы, как в императивных языках. В них нет главной фишки массивов: доступа к любому элементу за константное время, и изменения любого элемента за константное время.
Более того любая модификация потребует полного копирования массива и, соответственно, времени O(n).
Поэтому эти массивы нигде не используются :)

рекурсивные функции с аккумуляторами
подобрать удачные примеры, накодить несколько в емаксе
- фильтрация списка юзеров
- получение имен юзеров
- еще

** TODO записать видео

** TODO quiz

** TODO упражения
реализациия некоторых функций из модуля lists:
any, all, length, reverse, filter, map
что еще?
Можно брать упражения из книжки по хаскелю Макеева, там хорошие

** TODO попросить, чтобы сделали track для моего курса



* TODO 3й урок



* TODO 4й урок



* TODO Распиарить курс
- запостить инфу:
  - в чат эрлангистов
  - в гуглоплюс, beug и своя лента
  - в фейсбук
  - в гуглогруппу эрлангистов
- сделать раздел на своем сайте со списком всех уроков и ссылками на них


* По каждому уроку:

- теория, написать все в md-файл
  источники инфы:
  - Армстронг
  - Цезарини
  - Хеберт
  - OTP in action
  - yzh44yzh.by, erlang-school
  - notes.org

- подготовить презентацию
  - последний слайд: summary, о чем рассказывалось в уроке

- записать видео с помощью google hangout
  нужно будет переключаться между 3-мя окнами, что хреново
  попробовать либо емакс + в нем shell, в нем erl
  либо терминал и в нем консольный емакс

- quiz (один или несколько)

- практическое задание (одно или несколько)
  идеи упражнений можно брать:
  - у Цезарини есть упражнения
  - этюды для Erlang (там в основном лаже, но вдруг что-то найдется)
  - в книгах по Хаскелю есть упражнения. У Макеева.


* сделать прикольную картинку для курса
  сейчас это не поддерживается, но, может быть, будет
  нужен кот за компьютером
  нарисовать сперва на бумаге вручную, затем в гимпе


* Инфа

Мой ключ: 92c8c0b6809753e0e2bae19ff46f647b
похоже уже не нужен

Дока:
http://feedback.hexlet.io/knowledgebase

пока актуально только это
http://feedback.hexlet.io/knowledgebase/articles/470066-creating-lessons-and-exercises
тут не написано, что make bash запускает шел внутри докера, и там, наконец, доступны исходники упражения
и Makefile для них

Dockerfile для установки Erlang, Rebar, Relx
https://registry.hub.docker.com/u/correl/erlang/dockerfile/
