
* TODO попробовать создать упражнения, как написано тут
  http://feedback.hexlet.io/knowledgebase/articles/470066-creating-lessons-and-exercises

** Login to Hexlet via Bitbucket

** Add new exercise repository url and build

** ну и в конечном итоге нужно попробовать свое упражнение через hexlet web IDE

* TODO course.org мета-инфу о курсе
  + продумать и расписать получше
  - отредактировать на hexlet.org через веб-интерфейс
  - сделать прикольную картинку для курса

* TODO Попробовать создавать парочку quiz
  Их надо делать прикольными, с прикольными вариантами ответов

* TODO отредактировать мой профиль на hexlet.org
  Больше написать об авторе (блог, гуглоплюс, ютуб и т.д.)

* TODO распланировать, какие будут уроки
  https://github.com/yzh44yzh/erlang-school/blob/master/syllabus.org
  https://github.com/yzh44yzh/erlang-school/blob/master/TODO.org
** как будут группироваться уроки в темы?
   В курсе должна быть работа с БД: PostgreSQL, MySQL, Poolboy.
   Работа с json: jsonx, ej.
   Причем все это в первой части :)
** дедлайнты
   примерно прикинуть, к какому сроку будет готов каждый урок
   (релизить 1 урок в неделю, по воскресеньям)
   поставить дедлайны по каждой теме
   и дедлайн для всего курса.
** Можно разбить на 2 части, и зарелизить 1 часть раньше.
   Во вторую пойдут темы, за которые я еще не брался: common test, release и т.д.


* TODO попробовать Kazam для записи видео, может так будет удобнее.
  хотя он не пишет с веб-камеры

* TODO анонсировано, что какие-то практические задания можно будет выполнять прямо в браузере.
  Типа будет аналог REPL-консоли. Что, и для Erlang тоже?
  Нужно выяснить, что там будет.


* По каждому уроку:

- теория, написать все в md-файл
- видео
  - подготовить презентацию
  - потренировать в консоли, что хочу показать
  - потренировать в емаксе + сборку, что хочу написать
  - записать с помощью google hangout
    нужно будет переключаться между 3-мя окнами, что хреново
    попробовать либо емакс + в нем shell, в нем erl
    либо терминал и в нем консольный емакс
- quiz
- практическое задание (это отдельным репозиторием на bitbucket)

- потом создать урок через веб-интерфейс hexlet:
  - скопипастить мета-данные курса (аудитория, цель и т.д.)
  - дать ссылку на видео
  - скопипастить теорию
  - скопипастить quiz
  - добавить урок
  - добавить практику и привязать к уроку
  - добавить урок в курс

* Инфа

Мой ключ: 92c8c0b6809753e0e2bae19ff46f647b
наверное уже не нужен

Дока:
http://feedback.hexlet.io/knowledgebase

пока актуально только это
http://feedback.hexlet.io/knowledgebase/articles/470066-creating-lessons-and-exercises
тут не написано, что make bash запускает шел внутри докера, и там, наконец, доступны исходники упражения
и Makefile для них

Dockerfile для установки Erlang, Rebar, Relx
https://registry.hub.docker.com/u/correl/erlang/dockerfile/
