* TODO 5й урок KV-структуры данных
  SCHEDULED: <2015-02-21 Суб>

- практическое задание
  сделал, но оно пока не собирается

Просьба тем кто делает уроки, обновить инфраструктуру. В папке
hexlet-vagrant сделайте make build. Убедитесь что после этого внутри
вагранта стоит docker версии 1.5.0. Если это не так, то aptitude
install lxc-docker-1.5.0

- видео


* TODO 6й урок KV-структуры данных, продолжение
  SCHEDULED: <2015-02-28 Суб>
- теория
- quiz
- практическое задание
- видео


* По каждому уроку:

- источники инфы:
  - notes.org
  - erlang-school
  - официальные доки
  - Армстронг
  - Цезарини
  - Хеберт
  - OTP in action
  - yzh44yzh.by

- теория, написать все в md-файл

- quiz

- практическое задание (одно или несколько)
  идеи упражнений можно брать:
  - у Цезарини есть упражнения
  - этюды для Erlang (там в основном лаже, но вдруг что-то найдется)
  - в книгах по Хаскелю есть упражнения. У Макеева есть лабораторные работы.
  - мои либы на гитхабе

- записать видео


* Инфа

Дока:
http://feedback.hexlet.io/knowledgebase

Dockerfile для установки Erlang, Rebar, Relx
https://registry.hub.docker.com/u/correl/erlang/dockerfile/
