* TODO 6й урок KV-структуры данных, продолжение
  SCHEDULED: <2015-03-16 Mon>
- практическое задание
  + реализация
  + тесты
  + отдельный запуск каждого теста
  - README, spellcheck
  - запушить и прикрепить к уроку

* TODO обновить инфраструктуру
  SCHEDULED: <2015-03-09 Mon>
Просьба тем кто делает уроки, обновить инфраструктуру. В папке
hexlet-vagrant сделайте make build. Убедитесь что после этого внутри
вагранта стоит docker версии 1.5.0. Если это не так, то aptitude
install lxc-docker-1.5.0

Мы поменяли имя базового образа, переходите постепенно на FROM hexlet/hexlet-exercise-kit

На работе это сделал, все ок. Дома vagrant up не запускается.
Нужно снести hexlet-vagrant, скачать его заново, и по этому тутору
http://feedback.hexlet.io/knowledgebase/articles/470066
все заново настроить


* TODO улучшить практику
  SCHEDULED: <2015-03-10 Tue>
  печальная статистика прохождений
[18.14.40] Yura Zhloba: но вот сделать практику к первому уроку совсем уж простой
[18.15.06] Yura Zhloba: и разбить на 2 урока и на отдельные тесты, это да, не повредит
[18.15.16] Yura Zhloba: там, насколько я помню, штук 8 заданий
[18.15.39] Yura Zhloba: человек может сделать 7, застопориться на одном, и тесты не проходят, урок не пройдет, и я не знаю, в чем дело

По остальным урокам:
- подумать, может разбить практику на 2-3 части
- отдельный тест по каждому заданию
- в и README добавить примеры, как интерпретировать сообщения об ошибках, которые генерируют тесты

и поправить этот тест в первом упражнении
?assertEqual(true, is_equal(3.51, 3.51, 0.01)),
?assertEqual(true, is_equal(3.501, 3.502, 0.001)),


* TODO конспекты для всех уроков

* TODO 7й урок io_list, binary, string, unicode
  SCHEDULED: <2015-03-18 Срд>
- теория
- quiz
- практическое задание
- конспект теории
- видео


* По каждому уроку:

- источники инфы:
  - notes.org
  - erlang-school
  - официальные доки
  - Армстронг
  - Цезарини
  - Хеберт
  - erlang in anger
  - OTP in action
  - yzh44yzh.by

- теория
- quiz
- практическое задание
- распечатать теорию
- видео

* Инфа

Дока:
http://feedback.hexlet.io/knowledgebase

Dockerfile для установки Erlang, Rebar, Relx
https://registry.hub.docker.com/u/correl/erlang/dockerfile/
