* TODO улучшить практику
  SCHEDULED: <2015-03-14 Суб>
По первому уроку:
- еще упростить задание, убрать часть функций
- подробнее README
  - комментарий по каждой функции
  - пояснить, что нужно сделать заглушку на каждую функцию, чтобы код собрался
    (или что-то с этим придумать). Может разнести все в разные модули.
  - пояснить, как читать сообщения об ошибках
- поправить этот тест в первом упражнении
  ?assertEqual(true, is_equal(3.51, 3.51, 0.01)),
  ?assertEqual(true, is_equal(3.501, 3.502, 0.001)),

По всем урокам:
- в README отдельный комментарий по каждому заданию
- отдельный запуск теста по каждому заданию


* TODO конспекты для всех уроков

* TODO обновить инфраструктуру
  SCHEDULED: <2015-03-16 Пан>
Просьба тем кто делает уроки, обновить инфраструктуру. В папке
hexlet-vagrant сделайте make build. Убедитесь что после этого внутри
вагранта стоит docker версии 1.5.0. Если это не так, то aptitude
install lxc-docker-1.5.0

На работе это сделал, все ок. Дома vagrant up не запускается.
Нужно снести hexlet-vagrant, скачать его заново, и по этому тутору
http://feedback.hexlet.io/knowledgebase/articles/470066
все заново настроить

* TODO 7й урок io_list, binary, string, unicode
  SCHEDULED: <2015-03-18 Срд>
- теория
- quiz
- практическое задание
- конспект теории
- видео


* TODO курсовая работа по 1й части курса
  важно как-то это уметь тестировать
  веб-сервер пока не изучали, на UI расчитывать не приходится
  так что это должно быть что-то консольное
  консольная игра

* По каждому уроку:

- источники инфы:
  - notes.org
  - erlang-school
  - официальные доки
  - Армстронг
  - Цезарини
  - Хеберт
  - erlang in anger
  - OTP in action
  - yzh44yzh.by

- теория
- quiz
- практическое задание
- распечатать теорию
- видео

* Инфа

Дока:
http://feedback.hexlet.io/knowledgebase

Dockerfile для установки Erlang, Rebar, Relx
https://registry.hub.docker.com/u/correl/erlang/dockerfile/
