
* TODO попробовать создать упражнения, как написано тут
  http://feedback.hexlet.io/knowledgebase/articles/470066-creating-lessons-and-exercises
  Ну и будет ли там работать Erlang? Это надо просто попробовать.

* TODO Я залогинился на hexlet через гитхаб. Если залогинюсь через bitbucket, это будет другой аккаунт?
  аккаунт идентифицируется по имейлу, один имейл – один аккаунт, вне зависимости от способа входа
  надо попробовать

* TODO Разобраться, как создавать quiz
  Их надо делать прикольными, с прикольными вариантами ответов

* TODO cource.org мета-инфу о курсе
  - продумать и расписать получше
    https://github.com/yzh44yzh/erlang-school/blob/master/README.md
  - отредактировать на hexlet.org через веб-интерфейс
  - сделать прикольную картинку для курса

* TODO отредактировать мой профиль на hexlet.org
  Больше написать об авторе (блог, гуглоплюс, ютуб и т.д.)

* TODO распланировать, какие будут уроки
  https://github.com/yzh44yzh/erlang-school/blob/master/syllabus.org
  https://github.com/yzh44yzh/erlang-school/blob/master/TODO.org
  примерно прикинуть, к какому сроку будет готов каждый урок
  (релизить 1 урок в неделю, по воскресеньям)
  как будут группироваться уроки в темы? поставить дедлайны по каждой теме
  и дедлайн для всего курса

* TODO попробовать Kazam для записи видео, может так будет удобнее.
  хотя он не пишет с веб-камеры

* TODO анонсировано, что какие-то практические задания можно будет выполнять прямо в браузере.
  Типа будет аналог REPL-консоли. Что, и для Erlang тоже?
  Нужно выяснить, что там будет.


* По каждому уроку:

- теория, написать все в md-файл
- видео
  - подготовить презентацию
  - потренировать в консоли, что хочу показать
  - потренировать в емаксе + сборку, что хочу написать
  - записать с помощью google hangout
    нужно будет переключаться между 3-мя окнами, что хреново
    попробовать либо емакс + в нем shell, в нем erl
    либо терминал и в нем консольный емакс
- quiz
- практическое задание (это отдельным репозиторием на bitbucket)

- потом создать урок через веб-интерфейс hexlet:
  - скопипастить мета-данные курса (аудитория, цель и т.д.)
  - дать ссылку на видео
  - скопипастить теорию
  - скопипастить quiz
  - добавить урок
  - добавить практику и привязать к уроку
  - добавить урок в курс

* Инфа

Мой ключ: 92c8c0b6809753e0e2bae19ff46f647b
наверное уже не нужен

Дока:
http://feedback.hexlet.io/knowledgebase
пока актуально только это
http://feedback.hexlet.io/knowledgebase/articles/470066-creating-lessons-and-exercises
