Ко всем урокам сделать презентации в формате [remark](https://remarkjs.com/#1)

Таблица:
название темы / содержание + ДЗ / материалы тренера
где-то нужно заполнить excel

Добавить темы:

- cowboy, http service
  роутинг, хендлер

- работа с БД (postgresql, mysql)
  драйвер, пул, реконнекты

- курсовой проект на выходе:
  http-сервис, БД, git
  куда-то надо деплоить
  соединиться с фронтендом

расписать, сколько часов нужно на каждую тему

курс в идеальных условиях (маленькая группа, сильные разработчики) проходится за 20 часов
будем расчитывать, что студентам нужно в 2 раза больше -- 40 часов

Одно занятие будет 2 либо 3 часа.

erlang + windows -- проверить все упражнения

* 00
нужно обновить usage.md.pdf.pptx
более актуальная инфа про WhatsUp
недостатки про "мало библиотек", "медленно развивается" -- это неправда


* 08. concurrency

картинка-схема, как работает почтовый ящик

добавить про exit(Pid, shutdown)

Подготовить к практике MapReduce. Схема как можно наладить общение между потоками.
Должна быть в README.


* 09. gen_server_1
- схема из 4х квадратов, как в gen_server_2 только для нашей кастомной реализации


* 10. gen_server_2
схема deadlock
прямой и через цепочку вызовов


* 12. supervisor
simple_one_for_one, можно ли остановить/удалить child?

убрать старые версии init, оставить только новые, на мапах


* 13. Application
- показывать observer. На примере solution или на каком-нибудь другом примере.


* 14. OTP
- структуру проекта на примере rebar3 а не rebar2
- показать wgnet либы
- cowboy, cowlib, ranch -- пример OTP приложений
- схема -- проблема с транзитивными либами


* 15. обработка ошибок
- рассказать про pipeline
- показать, как это выглядит на OCaml (Haskell)
https://github.com/yzh44yzh/erl_fun_composition
