compile:
	erlc *.erl

quick_start:
	erl -pa ~/p/cowboy/ebin -pa ~/p/cowboy/deps/*/ebin -s try_cowboy start

run:
	erl -pa ~/p/cowboy/ebin -pa ~/p/cowboy/deps/*/ebin -s try_routing start


clean:
	-rm *.beam
	-rm erl_crash.dump
